# Generated by Django 5.0.1 on 2024-02-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.TextField(max_length=100, null=True)),
                ('firstname', models.TextField(max_length=100, null=True)),
                ('lastname', models.TextField(max_length=100, null=True)),
            ],
        ),
    ]
